- name: Codecov
  uses: codecov/codecov-action@v1.0.6
  with:
    # User defined upload name. Visible in Codecov UI
    name: michael williams
    # Repository upload token - get it from codecov.io. Required only for private repositories
    token: 
    # Path to coverage file to upload
    file: # optional
    # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
    flags: # optional
    # Specify whether or not CI build should fail if Codecov runs into an error during upload
    fail_ci_if_error: false
