# This is a basic workflow to help you get started with Actions

name: Node.js CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: Use Node.js ${{ matrix.node-version }}
    # - name: Codecov-coverage
      uses: codecov/codecov-action@v1.0.6
        uses: actions/setup-node@v1.0.6
      with:
        node-version: ${{ matrix.node-version }}
      with:
        # User defined upload name. Visible in Codecov UI
        name: hacker-flow-coverage
        # Repository upload token - get it from codecov.io. Required only for private repositories
        token: ${{secrets.CODECOV_TOKEN}}
        # Path to coverage file to upload
        file: '../../coverage/'
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        flags:  # optional
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: false
# codecov:
#   token: ${{secrets.CODECOV_TOKEN}}
#   require_ci_to_pass: yes

# coverage:
#   precision: 2
#   round: down
#   range: "70...100"

# parsers:
#   gcov:
#     branch_detection:
#       conditional: yes
#       loop: yes
#       method: no
#       macro: no

# comment:
#   layout: "reach,diff,flags,tree"
#   behavior: default
#   require_changes: no
